name: Update STL files

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install openscad
        run: |
          sudo apt-get install -y --no-install-recommends openscad

      - name: Generate STL files
        run: make

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
